kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: node
    app: flannel
    release: {{ .Release.Name }}
data:
  cni-conf.json: |
    {{ toJson .Values.cniConf }}
  net-conf.json: |
    {
{{- if .Values.podCidr }}
      "Network": {{ .Values.podCidr | quote }},
      "SubnetLen": {{ default 24 .Values.subnet.ip4.length }},
{{- if .Values.subnet.ip4.min }}
      "SubnetMin": {{ .Values.subnet.ip4.min | quote }},
{{- end }}
{{- if .Values.subnet.ip4.max }}
      "SubnetMax": {{ .Values.subnet.ip4.max | quote }},
{{- end }}
{{- else }}
      "EnableIPv4": false,
{{- end }}
{{- if .Values.podCidrv6 }}
      "IPv6Network": {{ .Values.podCidrv6 | quote }},
      "IPv6SubnetLen": {{ default 64 .Values.subnet.ip6.length }},
{{- if .Values.subnet.ip6.min }}
      "IPv6SubnetMin": {{ .Values.subnet.ip6.min | quote }},
{{- end }}
{{- if .Values.subnet.ip6.max }}
      "IPv6SubnetMax": {{ .Values.subnet.ip6.max | quote }},
{{- end }}
      "EnableIPv6": true,
{{- end }}
      "Backend": {
{{- if eq .Values.flannel.backend "vxlan" }}
{{- if .Values.flannel.backendPort }}
        "Port": {{ .Values.flannel.backendPort }},
{{- end }}
{{- if .Values.flannel.vni }}
        "VNI": {{ .Values.flannel.vni }},
{{- end }}
{{- if .Values.flannel.GBP }}
        "GBP": {{ .Values.flannel.GBP }},
{{- end }}
{{- if .Values.flannel.directRouting }}
        "DirectRouting": {{ .Values.flannel.directRouting }},
{{- end }}
{{- if .Values.flannel.mtu }}
        "MTU": {{ .Values.flannel.mtu }},
{{- end }}
{{- if .Values.flannel.macPrefix }}
        "MacPrefix": {{ .Values.flannel.macPrefix | quote }},
{{- end }}
        "Type": {{ .Values.flannel.backend | quote }}
{{- else if eq .Values.flannel.backend "wireguard" }}
{{- if .Values.flannel.backendPort }}
        "ListenPort": {{ .Values.flannel.backendPort }},
{{- end }}
{{- if .Values.flannel.backendPortv6 }}
        "ListenPortV6": {{ .Values.flannel.backendPortv6 }},
{{- end }}
{{- if .Values.flannel.psk }}
        "PSK": {{ .Values.flannel.psk | quote }},
{{- end }}
{{- if .Values.flannel.mtu }}
        "MTU": {{ .Values.flannel.mtu }},
{{- end }}
{{- if .Values.flannel.tunnelMode }}
        "Mode": {{ .Values.flannel.tunnelMode }},
{{- end }}
{{- if .Values.flannel.keepaliveInterval }}
        "PersistentKeepaliveInterval": {{ .Values.flannel.keepaliveInterval }},
{{- end }}
        "Type": {{ .Values.flannel.backend | quote }}
{{- else if eq .Values.flannel.backend "udp" }}
{{- if .Values.flannel.backendPort }}
        "Port": {{ .Values.flannel.backendPort }},
{{- end }}
        "Type": {{ .Values.flannel.backend | quote }}
{{- else }}
        "Type": {{ .Values.flannel.backend | quote }}
{{- end }}
      }
    }
